import type { ChecklistItemId, FlightType } from "./types";

export interface LessonPreset {
  key: string;
  title: string;
  description: string;
  flightType: FlightType;
  maxFratScore: number;
  objectives: string[];
  checklistItems: ChecklistItemId[];
}

export const LESSON_PRESETS: LessonPreset[] = [
  {
    key: "first-solo-prep",
    title: "First Solo Prep",
    description: "Pre-solo preparation: pattern work, emergencies, and go-arounds",
    flightType: "local",
    maxFratScore: 15,
    objectives: [
      "Demonstrate 3 consecutive unassisted landings",
      "Execute a proper go-around from short final",
      "Handle simulated engine failure in the pattern",
      "Make correct radio calls at all positions",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "tfrs",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "personal_minimums",
      "frat",
    ],
  },
  {
    key: "short-field-ops",
    title: "Short Field Ops",
    description: "Short and soft field takeoff/landing technique practice",
    flightType: "local",
    maxFratScore: 20,
    objectives: [
      "Perform short field takeoff within ACS standards",
      "Perform short field landing within 200ft of target",
      "Perform soft field takeoff maintaining back-pressure",
      "Perform soft field landing with no nosewheel skip",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "performance",
      "personal_minimums",
      "frat",
    ],
  },
  {
    key: "night-xc",
    title: "Night Cross-Country",
    description: "Night navigation and airport identification skills",
    flightType: "night",
    maxFratScore: 20,
    objectives: [
      "Navigate to destination using pilotage and VOR/GPS",
      "Identify airports and landmarks using lighting cues",
      "Execute proper night landing technique",
      "Demonstrate use of cockpit lighting and night vision preservation",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "tfrs",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "alternate",
      "departure_procedures",
      "arrival_procedures",
      "equipment",
      "personal_minimums",
      "frat",
    ],
  },
  {
    key: "instrument-approaches",
    title: "Instrument Approach Practice",
    description: "ILS, VOR, and RNAV approach procedures under the hood",
    flightType: "instrument",
    maxFratScore: 30,
    objectives: [
      "Fly an ILS approach to minimums within ACS standards",
      "Fly a VOR approach with correct timing and step-downs",
      "Fly an RNAV (GPS) approach with LPV guidance",
      "Execute a missed approach and hold as published",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "tfrs",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "alternate",
      "departure_procedures",
      "arrival_procedures",
      "performance",
      "equipment",
      "personal_minimums",
      "frat",
    ],
  },
  {
    key: "xc-solo-prep",
    title: "XC Solo Prep",
    description: "Cross-country solo preparation: flight planning, diversion, and lost procedures",
    flightType: "xc",
    maxFratScore: 15,
    objectives: [
      "Complete a full cross-country flight plan with navlog",
      "Navigate to checkpoint within 5nm and 5min tolerance",
      "Demonstrate diversion to an alternate airport",
      "Demonstrate lost procedure and use of flight following",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "tfrs",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "alternate",
      "departure_procedures",
      "arrival_procedures",
      "performance",
      "personal_minimums",
      "frat",
    ],
  },
  {
    key: "checkride-prep",
    title: "Checkride Prep",
    description: "Full practical test standards review and mock checkride",
    flightType: "checkride",
    maxFratScore: 15,
    objectives: [
      "Complete oral exam topics: airworthiness, weather, regulations",
      "Demonstrate all required maneuvers to ACS standards",
      "Demonstrate ADM and risk management throughout flight",
      "Complete cross-country planning with all required documents",
    ],
    checklistItems: [
      "weather_current",
      "weather_forecast",
      "notams",
      "tfrs",
      "wind_runway",
      "fuel_plan",
      "weight_balance",
      "alternate",
      "departure_procedures",
      "arrival_procedures",
      "performance",
      "equipment",
      "personal_minimums",
      "frat",
    ],
  },
];

/**
 * Common objectives by flight type for quick-add chips.
 */
export const COMMON_OBJECTIVES: Record<FlightType, string[]> = {
  local: [
    "Normal takeoff and landing",
    "Power-off stall recovery",
    "Power-on stall recovery",
    "Steep turns (45-degree bank)",
    "Ground reference maneuvers",
    "Emergency descent procedure",
    "Go-around from short final",
    "Simulated engine failure",
    "Forward slip to landing",
  ],
  xc: [
    "Complete navlog and flight plan",
    "Pilotage and dead reckoning",
    "VOR navigation tracking",
    "GPS direct-to navigation",
    "Diversion to alternate",
    "Lost procedure execution",
    "Flight following communications",
    "Fuel management and planning",
  ],
  night: [
    "Night takeoff technique",
    "Night landing with VASI/PAPI",
    "Airport identification by lighting",
    "Night vision preservation",
    "Night emergency procedures",
    "Cockpit lighting management",
  ],
  instrument: [
    "ILS approach to minimums",
    "VOR approach with step-downs",
    "RNAV (GPS) LPV approach",
    "Missed approach procedure",
    "Holding pattern entry and tracking",
    "Partial panel basic attitudes",
    "Unusual attitude recovery",
    "ATC communication and clearances",
  ],
  checkride: [
    "Oral exam preparation",
    "All required maneuvers review",
    "Cross-country planning documents",
    "Weight and balance computation",
    "Aeronautical decision making",
    "Risk management scenarios",
    "Emergency procedures review",
    "Systems knowledge demonstration",
  ],
};
