import { createPersistedStore } from "./middleware";
import type { FlightCategory } from "@/lib/api/types";

export interface RouteBriefingHistoryEntry {
  id: string;
  createdAt: number;
  waypoints: string[];
  flightType: "VFR" | "IFR";
  isAutoGenerated: boolean;
  totalDistanceNm: number;
  worstCategory: FlightCategory | null;
  legCount: number;
}

interface RouteHistoryState {
  entries: RouteBriefingHistoryEntry[];
  addEntry: (entry: Omit<RouteBriefingHistoryEntry, "id" | "createdAt">) => void;
  clearHistory: () => void;
}

export const useRouteHistoryStore = createPersistedStore<RouteHistoryState>(
  "route-history",
  (set, get) => ({
    entries: [],

    addEntry: (entry) => {
      const now = Date.now();
      const id = now.toString(36) + Math.random().toString(36).slice(2, 6);

      // Deduplicate: skip if same waypoints were added within 60s
      const existing = get().entries;
      const isDuplicate = existing.some(
        (e) =>
          e.waypoints.join(",") === entry.waypoints.join(",") &&
          now - e.createdAt < 60_000
      );
      if (isDuplicate) return;

      const newEntry: RouteBriefingHistoryEntry = {
        id,
        createdAt: now,
        ...entry,
      };

      set({
        entries: [newEntry, ...existing].slice(0, 20),
      });
    },

    clearHistory: () => set({ entries: [] }),
  }),
  {
    partialize: (state) => ({ entries: state.entries }),
  }
);
