import { useState, useCallback, useMemo, useRef, useEffect } from "react";
import {
  View,
  Text,
  Pressable,
  ScrollView,
  StyleSheet,
  Keyboard,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import Animated, { FadeInDown, FadeOut, SlideOutUp, useReducedMotion } from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import { useRouter } from "expo-router";
import {
  Navigation,
  ShieldAlert,
  AlertTriangle,
  AlertCircle,
  Compass,
} from "lucide-react-native";

import { useRouteBriefing } from "@/hooks/useRouteBriefing";
import { SkeletonCard } from "@/components/ui/Skeleton";
import { DynamicSkyBackground } from "@/components/background/DynamicSkyBackground";
import { FRATModal } from "@/components/frat/FRATModal";
import { calculateNavLog } from "@/lib/navlog/calculate";
import { useWBStore } from "@/stores/wb-store";
import { calcTotalWB } from "@/lib/wb/calculations";
import { colors } from "@/theme/tokens";
import { useTheme } from "@/theme/ThemeProvider";
import { useSceneStore } from "@/stores/scene-store";
import { generateWaypoints } from "@/lib/route/waypoint-generator";
import { useContentWidth } from "@/hooks/useContentWidth";
import { trackEvent } from "@/services/analytics";

// New components
import { RouteInputCard } from "@/components/route/RouteInputCard";
import { RouteResultsHeader } from "@/components/route/RouteResultsHeader";
import { RouteSummaryBar } from "@/components/route/RouteSummaryBar";
import { RouteMapVisualization } from "@/components/route/RouteMapVisualization";
import { NavLogSection } from "@/components/route/NavLogSection";
import { AddWaypointButton } from "@/components/route/AddWaypointButton";
import { RouteBriefingHistoryCard } from "@/components/route/RouteBriefingHistoryCard";
import { RouteAiBriefingCard } from "@/components/route/RouteAiBriefingCard";
import { GhostCard } from "@/components/ui/GhostCard";
import { useRouteHistoryStore } from "@/stores/route-history-store";
import { useRouteAiBriefing } from "@/hooks/useRouteAiBriefing";
import type { RouteBriefingHistoryEntry } from "@/stores/route-history-store";

import type { FlightCategory } from "@/lib/api/types";

export default function RouteScreen() {
  const { theme, isDark } = useTheme();
  const router = useRouter();
  const reducedMotion = useReducedMotion();
  const contentWidth = useContentWidth();
  const scene = useSceneStore((s) => s.scene);
  const aircraft = useWBStore((s) => s.aircraft);
  const stationWeights = useWBStore((s) => s.stationWeights);
  const fuelGallons = useWBStore((s) => s.fuelGallons);
  const fuelUnit = useWBStore((s) => s.fuelUnit);
  const customEmptyWeight = useWBStore((s) => s.customEmptyWeight);
  const customEmptyArm = useWBStore((s) => s.customEmptyArm);

  const [waypoints, setWaypoints] = useState<string[]>(["", ""]);
  const [submitted, setSubmitted] = useState<string[]>([]);
  const [showFRAT, setShowFRAT] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [flightType, setFlightType] = useState<"VFR" | "IFR">("VFR");
  const [showResults, setShowResults] = useState(false);
  const [pendingFRAT, setPendingFRAT] = useState(false);
  const wasAutoGenerated = useRef(false);

  const historyEntries = useRouteHistoryStore((s) => s.entries);
  const addHistoryEntry = useRouteHistoryStore((s) => s.addEntry);

  const { data: routeBriefing, isLoading, error: routeError, isError } = useRouteBriefing(submitted);

  // Compute hazard stations
  const hazardStations = useMemo(() => {
    if (!routeBriefing) return [];
    return routeBriefing.weatherPoints.filter(
      (wp) =>
        wp.metar &&
        (wp.metar.flightCategory === "MVFR" ||
          wp.metar.flightCategory === "IFR" ||
          wp.metar.flightCategory === "LIFR")
    );
  }, [routeBriefing]);

  // Set of hazard ICAOs for map
  const hazardIcaoSet = useMemo(
    () => new Set(hazardStations.map((h) => h.waypoint.icao)),
    [hazardStations]
  );

  // Category map for map markers
  const categoryMap = useMemo(() => {
    if (!routeBriefing) return {};
    const map: Record<string, FlightCategory> = {};
    for (const wp of routeBriefing.weatherPoints) {
      if (wp.metar?.flightCategory) {
        map[wp.waypoint.icao] = wp.metar.flightCategory;
      }
    }
    return map;
  }, [routeBriefing]);

  // Calculate NavLog
  const navLog = useMemo(() => {
    if (!routeBriefing) return null;
    return calculateNavLog(
      routeBriefing.legs,
      routeBriefing.weatherPoints,
      aircraft.cruiseSpeedKts,
      aircraft.fuelBurnRateGPH
    );
  }, [routeBriefing, aircraft.cruiseSpeedKts, aircraft.fuelBurnRateGPH]);

  // AI Route Briefing
  const { data: routeAiBriefing, isLoading: isAiBriefingLoading } =
    useRouteAiBriefing(routeBriefing?.weatherPoints, navLog);

  // W&B overweight check
  const wbResult = useMemo(
    () =>
      calcTotalWB(
        aircraft,
        stationWeights,
        fuelGallons,
        fuelUnit,
        customEmptyWeight,
        customEmptyArm
      ),
    [aircraft, stationWeights, fuelGallons, fuelUnit, customEmptyWeight, customEmptyArm]
  );
  const isOverweight = wbResult.isOverweight;
  const overweightBy = Math.round(
    wbResult.totalWeight - aircraft.maxTakeoffWeight
  );

  // Resolve waypoint objects from routeBriefing legs for the map
  const resolvedWaypoints = useMemo(() => {
    if (!routeBriefing || routeBriefing.legs.length === 0) return [];
    const wps = routeBriefing.legs.map((l) => l.from);
    // Add last destination
    const lastLeg = routeBriefing.legs[routeBriefing.legs.length - 1];
    wps.push(lastLeg.to);
    return wps;
  }, [routeBriefing]);

  // --- Handlers ---

  const updateWaypoint = (index: number, value: string) => {
    const updated = [...waypoints];
    updated[index] = value.toUpperCase();
    setWaypoints(updated);
    wasAutoGenerated.current = false;
  };

  const addWaypoint = () => {
    if (waypoints.length < 6) {
      Haptics.selectionAsync();
      setWaypoints([...waypoints, ""]);
    }
  };

  const removeWaypoint = (index: number) => {
    if (waypoints.length > 2) {
      Haptics.selectionAsync();
      setWaypoints(waypoints.filter((_, i) => i !== index));
    }
  };

  const clearWaypoints = useCallback(() => {
    Haptics.selectionAsync();
    setWaypoints(["", ""]);
    wasAutoGenerated.current = false;
  }, []);

  const handleSubmit = useCallback(() => {
    const valid = waypoints.filter((w) => w.trim().length >= 3);
    if (valid.length < 2) {
      Alert.alert(
        "Not Enough Waypoints",
        "Enter at least 2 valid airport identifiers (3-4 characters each)."
      );
      return;
    }
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setSubmitted(valid);
    Keyboard.dismiss();
    setPendingFRAT(true);
    trackEvent({ type: "route" });
  }, [waypoints]);

  // Show FRAT modal once route data arrives, or skip to error state
  useEffect(() => {
    if (!pendingFRAT) return;
    if (routeBriefing) {
      setShowFRAT(true);
      setPendingFRAT(false);
    } else if (isError) {
      setPendingFRAT(false);
      setShowResults(true);
    }
  }, [pendingFRAT, routeBriefing, isError]);

  const handleFRATContinue = useCallback(() => {
    setShowFRAT(false);
    setShowResults(true);

    if (routeBriefing) {
      // Determine worst flight category along route
      let worstCategory: FlightCategory | null = null;
      const categoryRank: Record<FlightCategory, number> = {
        VFR: 0,
        MVFR: 1,
        IFR: 2,
        LIFR: 3,
      };
      for (const wp of routeBriefing.weatherPoints) {
        if (wp.metar?.flightCategory) {
          const cat = wp.metar.flightCategory;
          if (!worstCategory || categoryRank[cat] > categoryRank[worstCategory]) {
            worstCategory = cat;
          }
        }
      }

      addHistoryEntry({
        waypoints: submitted,
        flightType,
        isAutoGenerated: wasAutoGenerated.current,
        totalDistanceNm: Math.round(routeBriefing.totalDistanceNm),
        worstCategory,
        legCount: routeBriefing.legs.length,
      });
    }
  }, [routeBriefing, submitted, flightType, addHistoryEntry]);

  const handleBack = useCallback(() => {
    setShowResults(false);
  }, []);

  const handleEdit = useCallback(() => {
    setShowResults(false);
  }, []);

  const handleAutoGenerate = useCallback(async () => {
    const departure = waypoints[0]?.trim().toUpperCase();
    const destination = waypoints[waypoints.length - 1]?.trim().toUpperCase();

    if (!departure || departure.length < 3) {
      Alert.alert(
        "Invalid Departure",
        "Please enter a valid departure airport identifier (3-4 characters)"
      );
      return;
    }

    if (!destination || destination.length < 3) {
      Alert.alert(
        "Invalid Destination",
        "Please enter a valid destination airport identifier (3-4 characters)"
      );
      return;
    }

    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setGenerating(true);

    try {
      const generatedWaypoints = await generateWaypoints(departure, destination, {
        strategy: "direct",
        maxSegmentNm: 25,
        flightType: flightType,
        corridorWidthNm: 30,
      });

      if (generatedWaypoints.length > 0) {
        const identifiers = generatedWaypoints.map((wp) => wp.identifier);
        setWaypoints(identifiers);
        wasAutoGenerated.current = true;
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

        if (identifiers.length <= 2) {
          Alert.alert(
            "Direct Route",
            `${departure} → ${destination} is a short route with no intermediate waypoints needed.`
          );
        }
      } else {
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
        Alert.alert(
          "No Route Generated",
          "Could not generate waypoints for this route. Try different airports or check your identifiers."
        );
      }
    } catch (error) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      Alert.alert(
        "Route Generation Failed",
        error instanceof Error
          ? error.message
          : "An unexpected error occurred. Please try again."
      );
    } finally {
      setGenerating(false);
    }
  }, [waypoints, flightType]);

  // Dynamic styles
  const hazardSubtitleColor = isDark ? "#fca5a5" : "#991b1b";
  const hazardStationIdColor = isDark ? "#fca5a5" : "#7f1d1d";
  const hazardDetailColor = isDark ? "#fca5a5" : "#991b1b";
  const gapTextColor = isDark ? "#fcd34d" : "#92400e";

  return (
    <View style={styles.container}>
      <DynamicSkyBackground scene={scene} />
      <SafeAreaView style={styles.safe} edges={["top"]}>
        <KeyboardAvoidingView
          behavior={Platform.OS === "ios" ? "padding" : "height"}
          style={{ flex: 1 }}
        >
        <ScrollView
          style={styles.scroll}
          contentContainerStyle={[
            styles.scrollContent,
            contentWidth ? { maxWidth: contentWidth } : undefined,
          ]}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* ==================== INPUT PHASE ==================== */}
          {!showResults && (
            <Animated.View exiting={reducedMotion ? undefined : FadeOut.duration(200).withCallback(() => {})}>
              {/* Header */}
              <Animated.View entering={reducedMotion ? undefined : FadeInDown} style={styles.header}>
                <View style={styles.titleRow}>
                  <Navigation size={22} color="#ffffff" strokeWidth={1.8} />
                  <Text style={styles.title}>Route Briefing</Text>
                </View>
              </Animated.View>

              {/* XC Wizard Link */}
              <Animated.View entering={reducedMotion ? undefined : FadeInDown.delay(25)}>
                <Pressable
                  onPress={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                    router.push("/xc-wizard");
                  }}
                  style={{
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: 8,
                    backgroundColor: "rgba(212,168,83,0.15)",
                    paddingVertical: 12,
                    borderRadius: 10,
                    borderWidth: 1,
                    borderColor: "rgba(212,168,83,0.25)",
                    marginBottom: 12,
                  }}
                >
                  <Compass size={16} color={colors.accent} />
                  <Text style={{ fontSize: 13, fontFamily: "SpaceGrotesk_600SemiBold", color: colors.accent }}>
                    XC Planning Wizard
                  </Text>
                </Pressable>
              </Animated.View>

              {/* Input Card */}
              <Animated.View entering={reducedMotion ? undefined : FadeInDown.delay(50)}>
                <RouteInputCard
                  waypoints={waypoints}
                  flightType={flightType}
                  generating={generating}
                  onUpdateWaypoint={updateWaypoint}
                  onAddWaypoint={addWaypoint}
                  onRemoveWaypoint={removeWaypoint}
                  onFlightTypeChange={setFlightType}
                  onAutoGenerate={handleAutoGenerate}
                  onClear={clearWaypoints}
                  onSubmit={handleSubmit}
                />
              </Animated.View>

              {/* Overweight Warning Banner (input phase) */}
              {isOverweight && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(30)}
                  style={styles.overweightBanner}
                >
                  <ShieldAlert size={16} color="#ffffff" />
                  <Text style={styles.overweightText}>
                    Aircraft is {overweightBy} lbs over MTOW (
                    {aircraft.maxTakeoffWeight} lbs). NavLog performance values
                    may be invalid.
                  </Text>
                </Animated.View>
              )}

              {/* Loading */}
              {isLoading && (
                <View style={styles.loadingCards}>
                  <SkeletonCard />
                  <SkeletonCard />
                </View>
              )}

              {/* Recent Briefings History */}
              {!isLoading && (
                <View style={{ marginTop: 16 }}>
                  {historyEntries.length > 0 ? (
                    <>
                      <Text style={styles.sectionHeader}>RECENT BRIEFINGS</Text>
                      {historyEntries.map((entry, idx) => (
                        <RouteBriefingHistoryCard
                          key={entry.id}
                          entry={entry}
                          index={idx}
                          onPress={(e) => {
                            setWaypoints(e.waypoints);
                            setFlightType(e.flightType);
                            wasAutoGenerated.current = e.isAutoGenerated;
                          }}
                        />
                      ))}
                    </>
                  ) : (
                    <GhostCard>
                      <Text
                        style={[
                          styles.emptyHistoryText,
                          { color: isDark ? "rgba(255,255,255,0.4)" : "#94a3b8" },
                        ]}
                      >
                        No recent briefings
                      </Text>
                    </GhostCard>
                  )}
                </View>
              )}
            </Animated.View>
          )}

          {/* ==================== RESULTS PHASE ==================== */}
          {showResults && routeBriefing && (
            <View>
              {/* Results Header */}
              <Animated.View entering={reducedMotion ? undefined : FadeInDown.delay(200)}>
                <RouteResultsHeader onBack={handleBack} onEdit={handleEdit} />
              </Animated.View>

              {/* Summary Bar */}
              <Animated.View
                entering={reducedMotion ? undefined : FadeInDown.delay(280)}
                style={{ marginTop: 8 }}
              >
                <RouteSummaryBar
                  totalDistanceNm={navLog?.totalDistance ?? routeBriefing.totalDistanceNm}
                  totalTimeMin={navLog?.totalTime ?? 0}
                  totalFuelGal={navLog?.totalFuel ?? 0}
                />
              </Animated.View>

              {/* Overweight Warning Banner (results phase) */}
              {isOverweight && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(300)}
                  style={styles.overweightBanner}
                >
                  <ShieldAlert size={16} color="#ffffff" />
                  <Text style={styles.overweightText}>
                    Aircraft is {overweightBy} lbs over MTOW (
                    {aircraft.maxTakeoffWeight} lbs). NavLog performance values
                    may be invalid.
                  </Text>
                </Animated.View>
              )}

              {/* AI Route Briefing */}
              {(routeAiBriefing || isAiBriefingLoading) && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(320)}
                  style={{ marginTop: 10 }}
                >
                  <RouteAiBriefingCard
                    briefing={routeAiBriefing}
                    isLoading={isAiBriefingLoading}
                  />
                </Animated.View>
              )}

              {/* Route Map */}
              {resolvedWaypoints.length >= 2 && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(350)}
                  style={{ marginTop: 12 }}
                >
                  <RouteMapVisualization
                    waypoints={resolvedWaypoints}
                    categoryMap={categoryMap}
                    hazardStations={hazardIcaoSet}
                  />
                </Animated.View>
              )}

              {/* Hazard Warning Card */}
              {hazardStations.length > 0 && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(400)}
                  style={styles.hazardCard}
                >
                  <View style={styles.hazardHeader}>
                    <ShieldAlert size={18} color="#ffffff" />
                    <Text style={styles.hazardTitle}>Hazard Warning</Text>
                  </View>
                  <Text
                    style={[styles.hazardSubtitle, { color: hazardSubtitleColor }]}
                  >
                    {hazardStations.length} station
                    {hazardStations.length > 1 ? "s" : ""} reporting sub-VFR
                    conditions along your route
                  </Text>
                  {hazardStations.map((wp) => {
                    const cat = wp.metar!.flightCategory;
                    const catColor =
                      cat === "LIFR"
                        ? colors.lifr
                        : cat === "IFR"
                        ? colors.ifr
                        : colors.mvfr;
                    return (
                      <View key={wp.waypoint.icao} style={styles.hazardStation}>
                        <View
                          style={[
                            styles.hazardDot,
                            { backgroundColor: catColor },
                          ]}
                        />
                        <Text
                          style={[
                            styles.hazardStationId,
                            { color: hazardStationIdColor },
                          ]}
                        >
                          {wp.waypoint.icao}
                        </Text>
                        <View
                          style={[
                            styles.hazardBadge,
                            { backgroundColor: catColor },
                          ]}
                        >
                          <Text style={styles.hazardBadgeText}>{cat}</Text>
                        </View>
                        <Text
                          style={[
                            styles.hazardDetail,
                            { color: hazardDetailColor },
                          ]}
                        >
                          Vis {wp.metar!.visibility.sm}
                          {wp.metar!.visibility.isPlus ? "+" : ""} SM
                          {wp.metar!.ceiling
                            ? ` · Ceil ${wp.metar!.ceiling.toLocaleString()} ft`
                            : ""}
                        </Text>
                      </View>
                    );
                  })}
                </Animated.View>
              )}

              {/* Gap Warnings */}
              {routeBriefing.gaps.map((gap, i) => (
                <Animated.View
                  key={i}
                  entering={reducedMotion ? undefined : FadeInDown.delay(420 + i * 50)}
                  style={styles.gapBanner}
                >
                  <AlertTriangle size={14} color={colors.alert.amber} />
                  <Text style={[styles.gapText, { color: gapTextColor }]}>
                    Data gap: {gap.fromWaypoint.icao} → {gap.toWaypoint.icao} (
                    {gap.gapDistanceNm} NM)
                  </Text>
                </Animated.View>
              ))}

              {/* NavLog Section */}
              {navLog && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(450)}
                  style={{ marginTop: 12 }}
                >
                  <NavLogSection
                    navLog={navLog}
                    weatherPoints={routeBriefing.weatherPoints}
                    baseDelay={500}
                  />
                </Animated.View>
              )}

              {/* Add Waypoint Button */}
              {waypoints.length < 6 && (
                <Animated.View
                  entering={reducedMotion ? undefined : FadeInDown.delay(600)}
                  style={{ marginTop: 16 }}
                >
                  <AddWaypointButton
                    onPress={() => {
                      addWaypoint();
                      setShowResults(false);
                    }}
                  />
                </Animated.View>
              )}
            </View>
          )}

          {/* Loading state when transitioning to results */}
          {showResults && !routeBriefing && isLoading && (
            <View>
              <Animated.View entering={reducedMotion ? undefined : FadeInDown.delay(200)}>
                <RouteResultsHeader onBack={handleBack} onEdit={handleEdit} />
              </Animated.View>
              <View style={styles.loadingCards}>
                <SkeletonCard />
                <SkeletonCard />
                <SkeletonCard />
              </View>
            </View>
          )}

          {/* Error state */}
          {showResults && !routeBriefing && !isLoading && isError && (
            <Animated.View entering={reducedMotion ? undefined : FadeInDown.delay(100)}>
              <View style={styles.errorCard}>
                <View style={styles.errorHeader}>
                  <AlertCircle size={20} color="#ffffff" />
                  <Text style={styles.errorTitle}>Route Briefing Failed</Text>
                </View>
                <Text style={styles.errorMessage}>
                  {routeError instanceof Error
                    ? routeError.message
                    : "An unexpected error occurred. Please check your identifiers and try again."}
                </Text>
                <Pressable
                  onPress={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                    setShowResults(false);
                  }}
                  style={styles.errorBtn}
                >
                  <Text style={styles.errorBtnText}>Edit Route</Text>
                </Pressable>
              </View>
            </Animated.View>
          )}

          <View style={{ height: 100 }} />
        </ScrollView>
        </KeyboardAvoidingView>
      </SafeAreaView>

      {/* FRAT Modal */}
      {routeBriefing && (
        <FRATModal
          visible={showFRAT}
          onClose={() => setShowFRAT(false)}
          onContinue={handleFRATContinue}
          routeBriefing={routeBriefing}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  safe: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    maxWidth: 500,
    width: "100%",
    alignSelf: "center" as const,
  },
  header: { paddingTop: 12, marginBottom: 16 },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  title: {
    fontSize: 22,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#ffffff",
    textShadowColor: "rgba(0,0,0,0.15)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  loadingCards: { gap: 12, marginTop: 12 },
  // ========== HAZARD WARNING CARD ==========
  hazardCard: {
    backgroundColor: "rgba(239,68,68,0.12)",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(239,68,68,0.3)",
    padding: 14,
    marginTop: 10,
  },
  hazardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
    backgroundColor: "rgba(239,68,68,0.85)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  hazardTitle: {
    fontSize: 13,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  hazardSubtitle: {
    fontSize: 11,
    fontFamily: "Inter_500Medium",
    marginTop: 4,
    marginBottom: 10,
  },
  hazardStation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(239,68,68,0.15)",
  },
  hazardDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  hazardStationId: {
    fontSize: 13,
    fontFamily: "JetBrainsMono_700Bold",
    width: 48,
  },
  hazardBadge: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hazardBadgeText: {
    fontSize: 10,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#ffffff",
    letterSpacing: 0.5,
  },
  hazardDetail: {
    fontSize: 10,
    fontFamily: "JetBrainsMono_400Regular",
    flex: 1,
    textAlign: "right",
  },
  // ========== GAP + OVERWEIGHT ==========
  gapBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(245,158,11,0.1)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.2)",
    padding: 10,
    marginTop: 8,
  },
  gapText: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    flex: 1,
  },
  overweightBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(239,68,68,0.85)",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "rgba(239,68,68,0.6)",
    padding: 12,
    marginTop: 10,
  },
  overweightText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#ffffff",
    flex: 1,
    lineHeight: 18,
  },
  sectionHeader: {
    fontSize: 11,
    fontFamily: "SpaceGrotesk_600SemiBold",
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  emptyHistoryText: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
  },
  // ========== ERROR CARD ==========
  errorCard: {
    backgroundColor: "rgba(239,68,68,0.12)",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(239,68,68,0.3)",
    padding: 16,
    marginTop: 12,
  },
  errorHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(239,68,68,0.85)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  errorTitle: {
    fontSize: 14,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#ffffff",
  },
  errorMessage: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#fca5a5",
    lineHeight: 19,
    marginBottom: 14,
  },
  errorBtn: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  errorBtnText: {
    fontSize: 13,
    fontFamily: "SpaceGrotesk_600SemiBold",
    color: "#ffffff",
  },
});
