import { View, Text, Pressable, StyleSheet } from "react-native";
import Animated, { FadeInLeft } from "react-native-reanimated";
import * as Haptics from "expo-haptics";

import { CloudCard } from "@/components/ui/CloudCard";
import { FlightCategoryBadge } from "@/components/ui/Badge";
import { colors } from "@/theme/tokens";
import { useTheme } from "@/theme/ThemeProvider";
import type { RouteBriefingHistoryEntry } from "@/stores/route-history-store";

interface RouteBriefingHistoryCardProps {
  entry: RouteBriefingHistoryEntry;
  index: number;
  onPress: (entry: RouteBriefingHistoryEntry) => void;
}

function formatTimestamp(ts: number): string {
  const date = new Date(ts);
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function RouteBriefingHistoryCard({
  entry,
  index,
  onPress,
}: RouteBriefingHistoryCardProps) {
  const { isDark } = useTheme();

  const accentColor = entry.isAutoGenerated
    ? colors.stratus[500]
    : colors.accent;

  const routeString = entry.waypoints.join(" \u2192 ");
  const subtitle = `${entry.flightType} \u00B7 ${entry.totalDistanceNm.toLocaleString()} NM \u00B7 ${entry.legCount} leg${entry.legCount !== 1 ? "s" : ""}`;
  const pillLabel = entry.isAutoGenerated ? "Auto" : "Manual";

  return (
    <Animated.View entering={FadeInLeft.delay(index * 40)}>
      <Pressable
        onPress={() => {
          Haptics.selectionAsync();
          onPress(entry);
        }}
      >
        <CloudCard
          style={{
            borderLeftWidth: 4,
            borderLeftColor: accentColor,
            marginBottom: 8,
          }}
        >
          {/* Row 1: Route + category badge */}
          <View style={styles.row1}>
            <Text
              style={[
                styles.routeText,
                { color: isDark ? "#ffffff" : "#083f6e" },
              ]}
              numberOfLines={1}
            >
              {routeString}
            </Text>
            {entry.worstCategory && (
              <FlightCategoryBadge category={entry.worstCategory} size="sm" />
            )}
          </View>

          {/* Row 2: Subtitle + timestamp */}
          <View style={styles.row2}>
            <View style={styles.subtitleRow}>
              <Text
                style={[
                  styles.subtitle,
                  { color: isDark ? "rgba(255,255,255,0.6)" : "#64748b" },
                ]}
              >
                {subtitle}
              </Text>
              <View
                style={[styles.pill, { backgroundColor: accentColor }]}
              >
                <Text style={styles.pillText}>{pillLabel}</Text>
              </View>
            </View>
            <Text
              style={[
                styles.timestamp,
                { color: isDark ? "rgba(255,255,255,0.4)" : "#94a3b8" },
              ]}
            >
              {formatTimestamp(entry.createdAt)}
            </Text>
          </View>
        </CloudCard>
      </Pressable>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  row1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  routeText: {
    fontSize: 13,
    fontFamily: "JetBrainsMono_700Bold",
    flex: 1,
  },
  row2: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  subtitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  subtitle: {
    fontSize: 11,
    fontFamily: "Inter_500Medium",
  },
  pill: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  pillText: {
    fontSize: 9,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#ffffff",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  timestamp: {
    fontSize: 10,
    fontFamily: "Inter_400Regular",
    marginLeft: 8,
  },
});
